// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foodcore.Models
{
    public partial class Feedback
    {
        public int Sino { get; set; }
        public string Productid { get; set; }
        public string Email { get; set; }
        public string Feedback1 { get; set; }

        public virtual Register EmailNavigation { get; set; }
        public virtual Product Product { get; set; }
    }
}