// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foodcore.Models
{
    public partial class Register
    {
        public Register()
        {
            Carts = new HashSet<Cart>();
            Feedbacks = new HashSet<Feedback>();
            Myorders = new HashSet<Myorder>();
        }

        public string Username { get; set; }
        public string Pwd { get; set; }
        public DateTime? Dob { get; set; }
        public string Email { get; set; }
        public bool? Gender { get; set; }
        public string Phone { get; set; }
        public string Nationality { get; set; }

        public virtual ICollection<Cart> Carts { get; set; }
        public virtual ICollection<Feedback> Feedbacks { get; set; }
        public virtual ICollection<Myorder> Myorders { get; set; }
    }
}